import type { Metadata } from "next"

import { Geist, Geist_Mono } from "next/font/google"

import { Toaster } from "@/src/components/ui/sonner"

import { ThemeProvider } from "../components/theme-provider"

import MainFooter from "./components/main-footer"
import MainNavbar from "./components/main-nav-bar"

import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          disableTransitionOnChange
          enableSystem
          attribute="class"
          defaultTheme="system"
        >
          <div className="flex min-h-screen flex-col items-center justify-center bg-zinc-50 font-sans dark:bg-black">
            <div className="flex w-full max-w-4xl flex-1 flex-col items-center bg-white px-2 sm:items-start sm:px-4 dark:bg-black">
              <MainNavbar />
              {children}
              <MainFooter />
            </div>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
